import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	alias: Object.fromEntries([
		"@codemirror/commands", "@codemirror/language", "@codemirror/state", "@codemirror/view",
		"@lezer/common", "@lezer/highlight", "@lezer/lr"
	].map(packageName => [packageName, path.resolve("node_modules", packageName)])),
	external: [
		"obsidian",
		"electron",
		...builtinModules,
		...builtinModules.map(module => `node:${module}`)],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
